### ISSUE TITLE
脚本搭建的代理全部失效了

### ISSUE THREAD

**Issue by InsaneFeel** [missuo/MTProxy#2]
你好，脚本搭建的代理好像都不可用了，重新搭建也不行，不知道问题出在哪里

**Comment by missuo** [comment]
晚点我看看
> 你好，脚本搭建的代理好像都不可用了，重新搭建也不行，不知道问题出在哪里

**Comment by InsaneFeel** [comment]
> 晚点我看看
> 
> > 好，手写的让你知道代表什么意思

好的，谢谢

**Comment by InsaneFeel** [comment]
> > 晚点我看看
> > > 好，手写的让你知道的代表什么
> 
> 好，谢谢

刚刚又恢复了，可能是TG除了什么问题....
