### ISSUE TITLE
默认secret怎么修改？

### ISSUE THREAD

**Issue by InsaneFeel** [missuo/MTProxy#3]
请问下怎么修改默认的secret，每次安装都是默认的secret强迫症表示很难受....

**Comment by missuo** [comment]
> 请问下怎么修改默认的secret，每次安装都是默认的secret强迫症表示很难受....

需要修改配置文件，未来我会考虑加入这个功能。待会回家我完善一下。

**Comment by missuo** [comment]
已经支持。 [#23c9462](https://github.com/missuo/MTProxy/commit/23c94621c7a24c305f408e0f2ca37549c2a26418)

**Comment by InsaneFeel** [comment]
> 已经支持。[#23c9462](https://github.com/missuo/MTProxy/commit/23c94621c7a24c305f408e0f2ca37549c2a26418)

感谢
